sonar.organization=elouafirmohamed
sonar.projectKey=mohamedElOuafir_suivi-interventions-app
sonar.host.url=https://sonarcloud.io
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.test.tsx